### PR TITLE
Simplify some code in InvocationMatcher class

### PR DESCRIPTION
**Pull request by deepj**

### CODE REVIEW

**Comment by rentalcustard** [comment]
I like what you're aiming for here, but your master doesn't pass the tests - can you run rake and get this passing?

**Comment by deepj** [comment]
```
citadela:matahari deepj$ rspec spec/matahari/invocation_spec.rb 
......

Finished in 0.00311 seconds
6 examples, 0 failures
citadela:matahari deepj$ rspec spec/matahari/invocation_matcher_spec.rb 
.......

Finished in 0.00581 seconds
7 examples, 0 failures
citadela:matahari deepj$ rspec spec/matahari/invocation_spec.rb 
......

Finished in 0.00136 seconds
6 examples, 0 failures
```

**Comment by rentalcustard** [comment]
The cukes fail - run rake.

**Comment by deepj** [comment]
Tom, please check it :)

**Comment by rentalcustard** [comment]
OK, looks good. I'll spend some time reviewing this and get it merged. Thanks!

**Comment by deepj** [comment]
Hi Tom, can you merge or drop this? I'm planning to commit some other code and solved issues today :)

**Comment by rentalcustard** [comment]
I'm away from my computer for a few days, can't you use a feature branch?

On 1 Sep 2011, at 09:08, deepj
reply@reply.github.com
wrote:

**Comment by deepj** [comment]
OK :)

**Pull request closed without merging**
